First part of trials ready for review
joemast/php-course pull request #1
Opened 2022-03-20 19:28 UTC by joemast

2022-03-22 04:49 UTC, ova777 requested changes

2022-03-22 04:49 UTC, ovaunit commented on src/Trials/BinarySum.php
> +function binarySum (string $arg1, string $arg2): string
После имени функции не должно быть пробела (isPowerOfThree аналогично)

2022-03-22 04:49 UTC, ova777 commented on tests/BinarySumTests.php
> +require_once "../src/Trials/BinarySum.php";
Если в строке нет переменных - нет смысла использовать двойные кавычки, лучше одинарные.
Аналогично в PowerOfThreeTests.php и ниже ("10", "01", ...)

2022-03-22 04:49 UTC, ova777 commented on src/Trials/PowerOfThree.php
> +function isPowerOfThree (int $int): bool
Для -3, -27 функция возвращает true, но эти числа не являются степенью тройки.

2022-03-22 05:25 UTC, joemast commented on src/Trials/PowerOfThree.php
> +function isPowerOfThree (int $int): bool
Это нечётные степени: -3 в 1 степени = -3, а -3 в 3 степени будет -27

2022-03-25 11:13 UTC, ova777 approved these changes

2022-03-31 16:12 UTC, merged