All trials with tests on PHPUnit
joemast/php-course pull request #5
Opened 2022-04-12 16:52 UTC by joemast

2022-04-29 03:32 UTC, ova777 requested changes

2022-04-29 03:32 UTC, ova777 commented on src/Trials/FizzBuzz.php
> +    private function isDiv5(int $num): bool
Вначале класса обычно размещают public-методы, потом protected, потом private.
Это нужно для того, что бы заглянув в класс сразу увидеть методы, которыми можно пользоваться снаружи, и не листать до них в конец.

2022-04-29 03:32 UTC, ova777 commented on tests/AddDigitsTest.php
> +            [1789, 7]
Не хватает запятой в конце

2022-04-29 03:32 UTC, ova777 commented on tests/AddDigitsTest.php
> +    public function testAddDigitsUsingTenDivision($number, $expected): void
Type hinting

2022-04-29 03:32 UTC, ova777 commented on tests/AddDigitsTest.php
> +    public function testAddDigitsUsingStringConversion($number, $expected): void
Type hinting

2022-04-29 03:32 UTC, ova777 commented on tests/BalancedBracketsTest.php
> +            ['((((()()))))', true]
Не хватает запятой в конце

2022-04-29 03:32 UTC, ova777 commented on tests/BinarySumTest.php
> +            'Args with leading/trailing spaces' => [' 111', '01 ', '1000']
Не хватает запятой в конце

2022-04-29 03:32 UTC, ova777 commented on tests/FibonacciTest.php
> +            [8, 21]
Не хватает запятой в конце

2022-04-29 03:32 UTC, ova777 commented on tests/FibonacciTest.php
> +            [11]
Не хватает запятой в конце

2022-04-29 03:32 UTC, ova777 commented on tests/PerfectNumbersTest.php
> +    public function testNumberIsPerfectUsingArray(int $number, bool $expected): void
Чем это отличается от testNumberIsPerfect? Не смог увидеть разницы.

2022-05-03 07:06 UTC, joemast commented on tests/PerfectNumbersTest.php
> +    public function testNumberIsPerfectUsingArray(int $number, bool $expected): void
Поправил. Ошибка копипасты )

2022-05-03 07:19 UTC, joemast commented on tests/AddDigitsTest.php
> +            [1789, 7]
Разве она нужна? По идее, PHP должен ругаться на отсутствие элемента массива после запятой. И то, что он этого не делает - это такой syntax sugar, чтобы упростить жизнь. Но не обязательное требование. То есть отсутствие запятой - это более правильно, но если она есть, PHP это прощает

2022-05-03 07:25 UTC, joemast commented on src/Trials/FizzBuzz.php
> +    private function isDiv5(int $num): bool
done

2022-05-03 07:25 UTC, joemast commented on tests/AddDigitsTest.php
> +            [1789, 7]
Добавил для единообразия, там где не было

2022-05-03 07:26 UTC, joemast commented on tests/AddDigitsTest.php
> +    public function testAddDigitsUsingTenDivision($number, $expected): void
done

2022-05-03 07:26 UTC, joemast commented on tests/AddDigitsTest.php
> +    public function testAddDigitsUsingStringConversion($number, $expected): void
done

2022-05-03 07:26 UTC, joemast commented on tests/BalancedBracketsTest.php
> +            ['((((()()))))', true]
done

2022-05-03 07:26 UTC, joemast commented on tests/BinarySumTest.php
> +            'Args with leading/trailing spaces' => [' 111', '01 ', '1000']
done

2022-05-03 07:26 UTC, joemast commented on tests/FibonacciTest.php
> +            [8, 21]
done

2022-05-03 07:26 UTC, joemast commented on tests/FibonacciTest.php
> +            [11]
done

2022-05-03 09:33 UTC, merged