Added logging feature with configuration and tests
joemast/php-course pull request #6
Opened 2022-05-10 09:41 UTC by joemast

2022-05-27 07:28 UTC, ovaunit requested changes

2022-05-27 07:28 UTC, ovaunit commented on config.php.tmpl
> +$config = [
Лучше делать `return [...];`, т.к. в твоем случае создается переменная `$config` в глобальной области видимости, а в каком-то случае может оказаться что и перезаписывается.

2022-05-27 07:28 UTC, ovaunit commented on src/PhpCourseApp.php
> +    private LoggerInterface $_logger;
Не нужно называть переменную начиная с `_`, так делали раньше когда не существовало модификаторов доступа, что бы показать она она приватная. Аналогично `$_logFileName` и `$_logger` в BinarySum

2022-05-27 07:28 UTC, ovaunit commented on src/Logger/ConsoleLogger.php
> +        print($message);
Мне кажется здесь стоит добавить перевод строки

2022-05-27 08:09 UTC, joemast commented on src/PhpCourseApp.php
> +    private LoggerInterface $_logger;
Мне линтер ругался. Я его видимо настроил проверять какие-то более широкие требования и вот он поругался, что приватные поля должны иметь подчеркивания в имени. Давай оставим так?

2022-05-31 17:57 UTC, ova777 approved these changes

2022-06-01 01:57 UTC, merged